version: "3.7"

networks:
  backend-network:
    driver: bridge
  aves-network:
    external: true

services:
  mysite:
    build:
      context: .
      dockerfile: Dockerfile-next
    image: flare-snapshot
    ports: 
      - 3000:3000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: flare
      NODE_ENV: production
    networks:
      - aves-network
      - backend-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    volumes:
      - ./SQL/db.sql:/docker-entrypoint-initdb.d/db_structure_only.sql
    environment:
        MYSQL_ROOT_PASSWORD: root
    networks:
      - backend-network